"""
Django settings for Espacios_eventos project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta # ¡Asegúrate de que esta importación esté al principio!

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tu_secret_key_aqui' # CAMBIA ESTO POR UNA KEY REAL EN PRODUCCIÓN

# WARNING: don't run with debug turned on in production!
DEBUG = True # Cámbialo a False en producción

ALLOWED_HOSTS = [] # En producción, añade tus dominios aquí


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tus aplicaciones
    'Espacios_app', # ¡Asegúrate de que el nombre de tu app sea correcto aquí!

    # Aplicaciones de terceros
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders', # Para manejar CORS, útil en desarrollo con un frontend separado
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # ¡Importante: debe ir antes de CommonMiddleware!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Espacios_eventos.urls' # Asegúrate de que esto apunte a tu archivo urls.py principal

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Añadimos una carpeta 'templates' en la raíz del proyecto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Espacios_eventos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co' # Cambiado a español de Colombia

TIME_ZONE = 'America/Bogota' # Zona horaria de Colombia

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuración de Usuario Personalizado ---
# Esto le dice a Django que use tu modelo de usuario personalizado en lugar del predeterminado.
AUTH_USER_MODEL = 'Espacios_app.CustomUser' # ¡Asegúrate de que este nombre sea correcto!

# --- Configuración de Django REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication', # Útil para el panel de administración
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny', # Permite acceso a la API por defecto
    ),
    'DEFAULT_RENDERER_CLASSES': ( # Hace que la API sea más legible en el navegador
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}

# --- Configuración de Django REST Framework Simple JWT ---
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60), # Tiempo de vida del token de acceso
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),   # Tiempo de vida del token de refresco
    "ROTATE_REFRESH_TOKENS": True,                 # Rotar el token de refresco con cada uso
    "BLACKLIST_ENABLED": True,                     # Habilitar la lista negra de tokens
    "UPDATE_LAST_LOGIN": True,                     # Actualizar el campo last_login del usuario

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,                     # Usar la SECRET_KEY de Django
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),              # Prefijo para el token JWT en el encabezado
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# --- Configuración de Django CORS Headers ---
# Permite peticiones desde cualquier origen (para desarrollo). En producción, especifica tus dominios.
CORS_ALLOW_ALL_ORIGINS = True 