# Generated by Django 5.2.3 on 2025-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espacios_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contrasenia',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador')], default='cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fechaPago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodoPago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_mantenimiento', 'En Mantenimiento'), ('no_disponible', 'No Disponible')], default='disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estadoPago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estadoReserva',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
    ]
